const MEAL_DATA = {
  beef: {
    breakfast: [
      "Steak and Eggs",
      "Beef Hash with Potatoes",
      "Corned Beef Hash",
      "Beef Breakfast Burrito",
      "Beef and Egg Scramble",
      "Philly Cheesesteak Omelette",
      "Beef Breakfast Tacos",
      "Steak Omelette",
      "Beef and Vegetable Scramble",
      "Ground Beef Breakfast Bowl",
      "Beef Biscuits and Gravy",
      "Beef Shakshuka",
      "Steak Hash",
      "Beef Frittata",
      "Beef and Pepper Egg Skillet"
    ],
    lunch: [
      "Classic Cheeseburger",
      "Roast Beef Sandwich",
      "Beef Tacos",
      "Beef Chili Bowl",
      "Beef and Rice Bowl",
      "Beef Stir Fry Rice",
      "French Dip Sandwich",
      "Beef Gyro Wrap",
      "Beef and Bean Burrito",
      "Beef Pho Soup",
      "Beef Quesadilla",
      "Philly Cheesesteak",
      "Beef Noodle Soup",
      "Beef Tostada",
      "Beef Nachos",
      "Beef Panini",
      "Beef Empanadas",
      "Beef and Potato Soup",
      "Beef Sliders",
      "Beef Stuffed Pita"
    ],
    dinner: [
      "Grilled Ribeye Steak",
      "Beef Pot Roast",
      "Beef Stew",
      "Beef Lasagna",
      "Beef Stir Fry",
      "Beef Enchiladas",
      "Spaghetti and Meatballs",
      "Beef Shepherd's Pie",
      "Beef Fried Rice",
      "Beef Kebabs",
      "Beef and Broccoli",
      "Beef Taco Bowl",
      "Beef Stroganoff",
      "Beef Wellington",
      "Beef Brisket",
      "Korean Beef Bowl",
      "Beef Fajitas",
      "Beef Bourguignon",
      "Beef Stuffed Peppers",
      "Beef Loin with Roasted Vegetables"
    ]
  },
  pork: {
    breakfast: [
      "Bacon and Eggs",
      "Pork Sausage Scramble",
      "Ham and Cheese Omelette",
      "Pork Breakfast Burrito",
      "Bacon Pancakes",
      "Ham and Egg Biscuit",
      "Sausage Gravy and Biscuits",
      "Canadian Bacon Eggs Benedict",
      "Pork Belly Hash",
      "BLT Breakfast Sandwich",
      "Pork and Apple Hash",
      "Chorizo and Egg Tacos",
      "Ham and Spinach Omelette",
      "Bacon and Avocado Toast",
      "Pork Sausage Breakfast Bowl"
    ],
    lunch: [
      "BLT Sandwich",
      "Ham and Swiss Sandwich",
      "BBQ Pulled Pork Sandwich",
      "Pork Tacos",
      "Pork Fried Rice",
      "Pulled Pork Nachos",
      "Ham and Bean Soup",
      "Pork Quesadilla",
      "Pork Banh Mi",
      "Ham and Cheese Croissant",
      "Italian Sausage Sub",
      "Pork Noodle Soup",
      "Pork Rice Bowl",
      "Pork Lettuce Wraps",
      "Chorizo Burrito",
      "Cuban Sandwich",
      "Pork and Cabbage Soup",
      "Pork Gyro",
      "Pork Belly Rice Bowl",
      "Ham Panini"
    ],
    dinner: [
      "Pork Chops with Mashed Potatoes",
      "BBQ Pork Ribs",
      "Pulled Pork Platter",
      "Pork Tenderloin with Vegetables",
      "Pork Stir Fry",
      "Pork Enchiladas",
      "Pork Roast with Root Vegetables",
      "Pork Dumplings",
      "Pork Fried Rice",
      "Pork and Sauerkraut",
      "Italian Sausage Pasta",
      "Pork Belly Ramen",
      "Pork Carnitas Tacos",
      "Stuffed Pork Loin",
      "Pork Chop Casserole",
      "Sweet and Sour Pork",
      "Pork Bolognese",
      "Honey Glazed Ham",
      "Pork and Vegetable Skewers",
      "Smoked Pork Shoulder"
    ]
  },
  chicken: {
    breakfast: [
      "Chicken and Waffles",
      "Chicken Breakfast Sandwich",
      "Chicken Sausage Scramble",
      "Chicken and Egg Burrito",
      "Chicken Hash with Peppers",
      "Chicken Veggie Omelette",
      "Chicken Breakfast Bowl",
      "Chicken Avocado Toast",
      "Chicken Egg Muffins",
      "Chicken Breakfast Tacos",
      "Grilled Chicken Protein Bowl",
      "Chicken and Sweet Potato Hash",
      "Chicken Frittata",
      "Chicken and Egg Wrap",
      "Chicken Shakshuka"
    ],
    lunch: [
      "Chicken Caesar Salad",
      "Grilled Chicken Sandwich",
      "Chicken Wrap",
      "Chicken Noodle Soup",
      "Chicken Tacos",
      "Chicken Fried Rice",
      "Chicken Quesadilla",
      "BBQ Chicken Pizza",
      "Chicken BLT",
      "Chicken Pita with Hummus",
      "Buffalo Chicken Wrap",
      "Chicken and Rice Bowl",
      "Chicken Caprese Sandwich",
      "Chicken Tostada",
      "Asian Chicken Salad",
      "Chicken Gyro",
      "Chicken Burrito Bowl",
      "Chicken Panini",
      "Teriyaki Chicken Wrap",
      "Chicken Soup"
    ],
    dinner: [
      "Roasted Whole Chicken",
      "Chicken Alfredo",
      "Chicken Parmesan",
      "Chicken Stir Fry",
      "Chicken Tikka Masala",
      "BBQ Chicken",
      "Chicken Enchiladas",
      "Chicken Pot Pie",
      "Lemon Herb Chicken",
      "Chicken Fried Rice",
      "Chicken Marsala",
      "Honey Garlic Chicken",
      "Chicken Piccata",
      "Teriyaki Chicken Bowl",
      "Chicken Skewers",
      "Chicken Cacciatore",
      "Butter Chicken",
      "Chicken Shawarma Bowl",
      "Chicken and Vegetable Bake",
      "Garlic Butter Chicken Thighs"
    ]
  },
  groundTurkey: {
    breakfast: [
      "Turkey Sausage and Eggs",
      "Turkey Scramble",
      "Turkey Breakfast Burrito",
      "Turkey and Egg Bowl",
      "Turkey Hash",
      "Turkey Mushroom Omelette",
      "Turkey Breakfast Bowl",
      "Turkey Avocado Toast",
      "Turkey Egg Muffins",
      "Turkey Breakfast Tacos",
      "Turkey Spinach Frittata",
      "Turkey Shakshuka",
      "Turkey and Potato Hash",
      "Turkey Egg Wrap",
      "Turkey Sausage Patties with Eggs"
    ],
    lunch: [
      "Turkey Burger",
      "Turkey Veggie Wrap",
      "Turkey Tacos",
      "Turkey Chili Bowl",
      "Turkey and Rice Bowl",
      "Turkey Meatball Sub",
      "Turkey Lettuce Wraps",
      "Turkey Club Sandwich",
      "Turkey Noodle Soup",
      "Turkey Quesadilla",
      "Turkey Avocado Wrap",
      "Turkey Pita Sandwich",
      "Turkey Caesar Salad",
      "Turkey Nacho Bowl",
      "Turkey Burrito Bowl",
      "Turkey Stuffed Pita",
      "Turkey Cranberry Sandwich",
      "Turkey and Bean Soup",
      "Turkey Rice Bowl",
      "Turkey Sliders"
    ],
    dinner: [
      "Turkey Meatballs with Pasta",
      "Turkey Burger and Sweet Potato Fries",
      "Turkey Stuffed Peppers",
      "Turkey Chili",
      "Turkey Tacos",
      "Turkey Meatloaf",
      "Turkey Stir Fry",
      "Turkey Enchiladas",
      "Turkey Shepherd's Pie",
      "Turkey Fried Rice",
      "Turkey Bolognese",
      "Turkey Vegetable Soup",
      "Turkey Kebabs",
      "Turkey Casserole",
      "Turkey Zucchini Boats",
      "Turkey Pot Pie",
      "Turkey Bean Chili",
      "Turkey and Rice Bake",
      "Turkey Piccata",
      "Turkey Stuffed Mushrooms"
    ]
  }
};
