name = "plateful"
main = "worker/index.js"
compatibility_date = "2024-09-23"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "plateful-auth"
database_id = "6b5d9fec-394d-4b46-99ef-44ff305578d3"
